import { default as React, Component } from "react";
import ArticleHeader from "./ArticleHeader";

import ScanComponent from "./Scan";
import Transformation from "../lib/Transformation";

export default class Article extends ScanComponent {

  setupTransformations(){
    let topOffset = new Transformation(0, 0.05, (pct) => {
                  return 140 - (pct * 140);
                }, { pre: 140, post: 130});

    let fixed = new Transformation(0,0.05, (pct) => {
        return true;
    }, {pre: true, post: false});

    return {
      topOffset,
      fixed
    };
  }

  mediaLink(evt) {
    this.props.setMedia(evt.currentTarget.hash);
  }

  detailLink(evt) {
    this.props.showDetails(evt.currentTarget.hash, { x: evt.pageX, y: evt.pageY });
  }

  articleLink(evt) {
    this.props.showRelatedArticles(evt.currentTarget.hash);
  }

  render() {
    const {topOffset, fixed} = this.getValues();

    var {topOffset, fixed} = this.getValues();

    return (
      <div ref="article" className="article" style={{top: `${topOffset}vh`, position: fixed ? "fixed" : "absolute"}}>
        <ArticleHeader headerClasses="article-header" title="The VICE Guide to New York City" byline="By VICE Travel Staff" />
        <div className="article-body">
          <p>First there were dinosaurs; then a montage of gangsters eating spaghetti and stabbing stuff with "Gimme Shelter" playing in the background; then the Ramones and some breakdancing; all culminating in a gentrified paradise that smells like brunch and has countless ratchet ATMs that spit your money into the street.</p>
          <p>The last point aside, as narratives for a city, you can do worse. There are apparently towns on this planet where hip-hop wasn't invented and Fania Records and Madball and Basquiat never existed.</p>
          <p>So, if you've just moved to New York or you're visiting, we'd like to help you. The following is what we would recommend to anyone willing to set cynicism aside and enjoy the capital city of planet Earth.</p>
          <p>It's also fucking huge, so this is not a definitive guide by any stretch, it's just a gussied up version of the email we send to people who visit from foreign VICE offices.</p>
          <h2>To the Five Boroughs</h2>
          <p>New York City is compromised of five boroughs. Manhattan (from "Mannahata," after Native American names for the area), Staten Island (Staten Eylandt after the States General), The Bronx (named after Jonas Bronck), Brooklyn (Breukelen, the Dutch village in the Netherlands), and Queens (after Queen Catherine of Braganza, wife of King Charles II of England).</p>
          <p>Yes, we cut and pasted that from the <a href="http://www.nyhistory.org/community/borough-names" target="_blank">New York Historical Society</a>.</p>
          <p>Long story short, boroughs are counties. We call them "boroughs" because presumably the original New Yorkers were rabbits. In "Touch It (remix 3)," Papoose refers to them as "the five boroughs of death," but you don't have to do that.</p>
          <a name="Neighborhoods"></a>
          <h2 data-scroll="true" data-scroll-action="#image#0">Neighborhoods We Like</h2>
          <p>There isn't a neighborhood in NYC that doesn't have something in it to recommend. You can probably skip the upper East and West sides (outside of Central Park excursions—definitely go watch the Central Park Dance Skaters Association and rediscover your long buried joy in life) because they're very expensive places that never really exceed "pleasant."</p>
          <p>You will notice that the listings in this guide tend towards the Williamsburg-centric. This is because VICE is headquartered there and, as it is already a wasteland of overpriced condominiums, we can advocate your running amuck in it with the clear conscience of a newborn babe. Go ahead, tag something. Tell the cops we said it was chill.</p>
          <p><strong>Bushwick</strong><br />This is probably the cheapest neighborhood in which to stay and socialize. It's currently in the throes of gentrification and its long time residents are justifiably a bit touchy. I'm not going to argue the pros and cons of the steady march of capital. Have a nice time. It's probably where you can afford to sleep and there's no shortage of new bars, clubs, and restaurants to explore, but please don't treat it like a college campus. Also, for the love of Pete, don't call the bustling (and definitely worth visiting) area off the Morgan stop "Morgantown." You're not in some walled-off society. You're in Bushwick.</p>
          <p><strong>Greenpoint</strong><br />A tree-lined utopia past McCarren Park, Greenpoint borders Williamsburg. It hasn't fallen under the dominium of the high-rise builders as of yet. This is where young media professionals meet local teens with heroin problems and tattoos of questionable politics who get a little shouty. Enjoy the view of the sky. Go get some pierogies.</p>
          <p><strong>West Village/East Village/Alphabet City</strong><br />Even ten years ago, there was a huge difference between these neighborhoods, but that's not really the case anymore. The East still has pockets of punk and/or Latin resistance (and Tompkins Square Park will never not be fun) and the West still has a few gay bars and some nice plaques commemorating dead writers, but really, it's all an unholy mess of college kids and their future selves. There's still good food and unduly pretty people and there's the Hells Angels Club house on 3rd Street (should you have your heart set on getting your face kicked in like it's 1986), but for the most part, "The Village" is NYU. Submit.</p>
          <p><strong>Harlem</strong><br />Arguably the most historically important neighborhood in New York City. White flight into Harlem has given the neighborhood a slight identity crises with new residents clashing with old. But from the Apollo Theatre to <a href="#map#malcolmxblvd" onClick={this.mediaLink.bind(this)}><strong>Malcolm X Blvd</strong></a>, Harlem is one of the few New York neighborhoods that has largely retained its flavor despite the encroachment of Babylon (though the Apollo now books acts like Neko Case too which is, you know, totally fine). Oh, yeah, there's also countless jazz clubs, the Langston Hughes Residence, <a href="#map#studiomuseum" onClick={this.mediaLink.bind(this)}><strong>the Studio Museum</strong></a>, and the best food imaginable. It would be strange not to visit. Don't be a chump.</p>
          <p><strong>Gowanus</strong><br />Gowanus is a strange and haunted neighborhood well worth the visit. The canal, all jokes and reality of its pollution aside, gives the place an air of gaslight mystery. Besides the scenery, it's home to <a href="#map#akashicbooks" onClick={this.mediaLink.bind(this)}><strong>Akashic Books</strong></a>, <a href="#map#bellhouse" onClick={this.mediaLink.bind(this)}><strong>The Bell House</strong></a>, and a number of new and generally rad restaurants.</p>
          <p><strong>Lower East Side</strong><br />You might know that Julian Casablancas song called "Ludlow Street," and well he's right, it used to be good and isn't really any more. But, stay the hell off of it and you can make LES work. Ludlow is now the sole purview of <strong><a href="http://www.musclefigures.com/" target="_blank">M.U.S.C.L.E.S.</a></strong> and human crepes, but Orchard running parallel is still a good time. If you cross Delancey and wander the borders of LES and Chinatown, you can almost feel the olde timey New York feeling of "holy shit...something might happen in my life...TONIGHT." Even if what actually happens is just a bad idea attached to a skateboard, let your heart beat a bit free.</p>
          <p><strong>Tribeca<br /></strong>There are two major reasons to visit downtown. You should go to the Reflecting Absence World Trade Center Memorial. People argue about the aesthetic of the new tower. It's inarguably a product of political compromise and its architectural height of 1,776 feet is empire kitsch, but frankly how the hell are you ever going to put anything on that site which will please everyone? Frankly, it's not so bad. The clouds reflect off it beautifully and from certain angles it's a stunner. More importantly, the waterfall pool that serves as the site's actual memorial is something to be experienced. It works in the same way the Vietnam Memorial works; the names, it's all in the names.</p>
          <p>The other site to pay respect to is the African Burial Ground National Monument, just a short walk from Ground Zero. The burial ground is on the land of New York's first African-American cemetery. The site was discovered in 1992 when a federal building was being built and it was only through community activism that construction was halted. So go bow your head to both the tragedy of the initial injustice and in respect to one of the few times basic morality prevailed over real estate interests.</p>
          <p>Look, if you're just interested in New York for "fun," invest in a slip 'n' slide and stay the fuck home. New York is not an amusement park. It's a deep city with a deeper history and all the death and glory that entails.</p>
          <p><a name="Etiquette"></a></p>
          <h2>Basic Etiquette</h2>
          <p>There is the grotesque stereotype of New Yorkers being unfriendly; rumor has it that you hold the door for a New Yorker, they will often say, "you must not be from New York." This is insane. ALL normal rules of etiquette hold true in New York. Pleases and thank yous and excuse mes, all of it. You just don't have to smile when you say all this. Nobody likes a phony. Just nod and be civil.</p>
          <p>If you get lost, don't be afraid to ask for directions. It may seem like New Yorkers walk at high speeds to avoid human contact, but they're not trying to be dicks. They've just got places to be. But here's a secret: Real New Yorkers LOVE giving directions. Don't be surprised if you stop someone to ask for help and three other people intervene with better routes. There's no greater pride than knowing the streets and subways inside out. Give the locals a chance to shine.</p>
          <p>Besides that? DON'T WALK IN THE FUCKING BIKE LANES. Look, yes, bikers can be terrible. When they ride on the sidewalk or run through red lights or, lord have mercy, when they bring their bikes on the subway when it's perfectly nice outside. Having said that, when you walk in the bike lane, you are basically saying, "Hey, delivery guy making less than minimum wage, I sure hope you die." Why would you say that? Walk on the sidewalk. Quickly please.</p>
          <p>Tip your bartenders. Especially you, Europeans. ESPECIALLY YOU, Australian dudes. WE KNOW YOU KNOW. Dollar a drink is customary but if you have some sort of principled stand on the injustice of that, just throw some loot down. Buybacks (that lovely ritual where the bartender will buy every third or fourth round for tipping customers) are not as prevalent as they used to be but they can still be had and you're not going to find out if you're a skinflint.</p>
          <p>Don't be weird around celebrities. A disappearing custom as even New Yorkers seem to have fallen under the poptimist spell of "giving a shit that someone is on TV," but you will, we promise, enjoy your New York experience so much more if you're not scaring the beejeezies out of Dave Attell outside the Comedy Cellar. You are cool. You have an innate worth entirely divorced from whatever fleetingly famous person you may see in the line to pee. We truly believe that. Act accordingly. Obviously, if they invite you into the bathroom with them, then that is your path and you must walk it.</p>
          <a name="Drink"></a>
          <h2 data-scroll="true" data-scroll-action="#image#3">Where to Drink/Party</h2>
          <p>Places to drink and party in NYC come and go with an almost impossible-to-fathom speed. That's why you'll see people who are devastated about clubs less than five-years-old closing. Five years feels like a very long time for a place to survive. Never underestimate a New Yorker's capacity for instant nostalgia. We miss you already. But for this section we're NOT mentioning places that will have a long line or will turn you away for not having a pretty face or proper attire.</p>
          <p>Caveat: These places lean towards the divey. That's the sort of bar that we believe New York excels at. BUT PLEASE NOTE, speakeasies are by definition illegal. You're not in a speakeasy, no matter what the guidebook tells you. We are just trying to live a life as free from corniness as possible.</p>
          <p><a href="#map#secondchancesaloon"><strong>Second Chance Saloon</strong></a><strong>:</strong> Staffed by many veterans of Williamsburg's much missed punk bar, Sweetwater Tavern, this is a no-nonsense drinking establishment with a superb jukebox and a staff that will, while probably not smiling, happily discuss sports and baseball with you. There's a pool table if you feel like getting into arguments with strangers.</p>
          <p><strong><a href="#map#oldrabbitclub" onClick={this.mediaLink.bind(this)}>124 Old Rabbit Club</a>:</strong> Belgian Beer Bar. Pitch black except for candles. Lots of loud, good music. We work out of here a lot. You don't have to threaten our life in the comments. You can come by and kill us yourself</p>
          <p><strong><a href="#map#scratcher" onClick={this.mediaLink.bind(this)}>The Scratcher</a>:</strong> East Village local where the bartenders pour the Guinness correctly. There's live music on Sunday nights that's usually comprised of touring Irish musicians, so be prepared for impromptu sing-alongs to go with your pint.</p>
          <p><strong><a href="#map#sidgold" onClick={this.mediaLink.bind(this)}>Sid Gold's Request Room</a>:</strong> Being a human person with a big heart, a substance abuse problem, and a sense of shame that waxes and wanes with the moon, you doubtlessly love karaoke. Hey, girl. Us, too. Sing someone else's body electric. The videos with the subtitles are nice, but it's time to up the ante and do live piano karaoke. Co-owner Joe McGinty, who for years has organized the songwriter tribute series, Loser's Lounge, leads the karaoke at Sid Gold's Request Room. McGinty has compiled an impressively diverse song list that, while perhaps not as overarching as your usual five-books-of-dreck-to-be-sung-ironically karaoke collection, still has something for everyone. Especially if your tastes run towards 70s AOR/R&amp;B and Nine Inch Nails. As we assume they do.</p>
          <p><strong><a href="#map#anbealbochtcafe" onClick={this.mediaLink.bind(this)}>An Beal Bocht Café</a>: </strong>Described as "the most Irish of Irish spots," An Beal Bocht is what you're going to do if you find yourself in The Bronx and have the overwhelming urge to pour one out for poor Joe Heaney. Good times for both ex-pats and those that like to ogle them. Good music and better than decent Irish pub food. They have bangers. They have mash.<br /></p>
          <p><strong>Cocktail Bars<br /></strong>Obviously no-one says mixology, someone just invented that word to make cocktails look stupid. That person was a dick and probably a misogynist, because obviously cocktails are great; they get you drunk and taste like raspberries. The only problem is that they take ages for the artisans behind the bar to make them, so if you want to drink them, please go to a place that specializes in them, don't try and walk the poor untrained bastard behind the bar through Empellon Cocina's Fat-Washed Mezcal while other people are trying to get a beer.</p>
          <p>To start with, <strong><a href="#map#deadrabbit" onClick={this.mediaLink.bind(this)}>The Dead Rabbit</a> </strong>and <a href="#map#dutchkills" onClick={this.mediaLink.bind(this)}><strong>Dutch Kills</strong></a> are fine, delicious options if you don't mind tucking in your shirt and want to drink like a steampunk.</p>
          <p>If you can't be bothered to slip out of your laundry day ensemble but you're still in the mood for a killer Old Fashioned, <a href="http://www.google.com/search?q=the+scratcher+new+york+city&amp;oq=the+scratcher+new+york+city&amp;aqs=chrome..69i57j69i64l3.4543j0j9&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Lucey%27s+Lounge+new+york+city" target="_blank"><strong>Lucey's Lounge</strong></a> welcomes you at the bar. The prices are reasonable, the freshly popped seasoned popcorn flows freely, and co-owner Henry mixes fast and clean.</p>
          <p>Maybe you want to pretend, if only for a moment, that you're a classNamey adult right out of an episode of <em>Mad Men</em>. Or maybe you just have to kill time before hopping a train to the suburbs to visit Aunt June. Why else would you be in Midtown? Make a stop at <a href="http://www.google.com/search?q=the+scratcher+new+york+city&amp;oq=the+scratcher+new+york+city&amp;aqs=chrome..69i57j69i64l3.4543j0j9&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Lantern%27s+Keep+new+york+city" target="_blank"><strong>Lantern's Keep</strong></a> at the Iroquois Hotel.</p>
          <p><strong>Other Bars/Parties<br /></strong><strong><a href="http://www.homesweethomebar.com/" target="_blank">Home Sweet Home</a> </strong>is a basement bar where your phone will not get service and you should go on Wednesdays or Fridays. Wednesday is the <a href="http://nothingchang/" target="_blank"><strong>Nothing Changes</strong></a> (formerly Wierd when run by artist Pieter Schoolworth) party. When it was Wierd it was a purist minimal synth party where goths drank Campari. Nothing Changes takes a slightly more freewheeling approach, but the party is regularly full of attractive people in kohl. There's a live band at midnight.</p>
          <p>Fridays is Jonathan Toubin's (of <a href="http://www.newyorknighttrain.com/" target="_blank"><strong>New York Night Train/Soul Clap</strong></a> fame) party. He plays all rare soul and funk 45s, often with guest DJs like Kid Congo Powers, James Chance, and Ian Svenonius. It can get extremely crowded, but with people who want to dance to old soul and funk, so it's delightful. Whatever you're thinking of requesting though? He doesn't have it.</p>
          <p><a href="https://interactive.vice.com/travel-guide-brooklyn-party-scene/" target="_blank"></a><a href="http://www.google.com/search?q=the+scratcher+new+york+city&amp;oq=the+scratcher+new+york+city&amp;aqs=chrome..69i57j69i64l3.4543j0j9&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Over+The+Eight+new+york+city" target="_blank"><strong>Over the Eight</strong></a><strong>:</strong> Owned by David Castillo, one of the main dudes at Saint Vitus, Over the Eight is a great place to listen to metal, goth, and hardcore while staring out the window. We can't stress enough how valuable and dwindling a commodity that is. There's a well-curated beer menu and Venezuelan street food served by Santa Salsa in the back, plus regular readings, karaoke, and live music. Fred, a dude from VICE, runs a monthly night there where we all spill beers on the decks while playing whatever is considered cool at that moment.</p>
          <p><strong><a href="www.tuesday-baby-tuesday.com/about.html" target="_blank">Tuesday, Baby Tuesday</a>:</strong> This party is the longest running of its kind in NYC. It started in 1993, the year Vince Staples was born and is still crazzzzzzy popular. In a country as bereft of old shit as this one, 22 years basically makes this our pyramids.</p>
          <p><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8" target="_blank"><strong>Tropical 128</strong></a><strong>:</strong> Tropical 128 is a tiki bar/pool hall with a secret weapon in <a href="https://twitter.com/" target="_blank"><strong>Prince Terrence</strong></a>. Terrence has been a downtown figure for years, throwing mixed parties that invariably are disgusting (in the good way). Prince Terrence will still play goth, new wave, and post punk, but Terry plays hip-hop.</p>
          <p><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Bossa+Nova+Civic+Club+new+york+city" target="_blank"><strong>Bossa Nova Civic Club</strong></a><strong>:</strong> The tropically themed Bushwick club has shockingly reasonable drink prices and brings in some of the best international and local DJs. It's generally where you need to go if you love techno and house, but don't want to be surrounded by seven trillion yahoos.</p>
          <p><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Apt.+78+new+york+city" target="_blank"><strong>Apt. 78</strong></a><strong>:</strong> A neighborhood restaurant/bar that over time, through an enviable roster of DJs like Schoolboy and Venus X, has become, in the words of DJ/musician Pal Frog, a.k.a. <a href="https://twitter.com/dances" target="_blank">Dances with White Girls</a>, "something important."</p>
          <p><strong>Saturdays at </strong><a href="http://www.tijuana-picnic.com/" target="_blank"><strong>Tijuana Picnic</strong></a><strong>:</strong> Speaking of Frog, he is the occasional guest DJ at this new regular "open forum, rap, cool stuff, rap" party by Scrap. Other guests include Sean Kinney of <a href="http://eddieeddiebybillytommy.com/" target="_blank"><strong>Eddie Eddie by Billy Tommy</strong></a> and <a href="https://twitter.com/pjofdon" target="_blank"><strong>PJ Monte</strong></a>. Expect girls dancing with each other, and a lot of <a href="http://bullettmedia.com/article/jeff-koons-vandal-is-a-member-of-a-notorious-nyc-graffiti-crew/" target="_blank"><strong>PPP</strong></a> alumni drinking. Maybe they'll sign your autograph book.</p>
          <p><a href="http://famousinbushwick.tumblr.com/" target="_blank"><strong>Famous in Bushwick</strong></a>: <a href="http://www.simplythegent.com/" target="_blank"><strong>Jimmy the Gent's</strong></a> multi purpose arts and music organization throws some of the best soul-satisfying hip-hop and affiliated arts parties around. One of the few roaming events that both underground rappers and get-lit-at-all-costs populists agree on.</p>
          <p><a href="http://www.facebook.com/VogueKnights" target="_blank"><strong>Vogue Knights</strong></a>: <a href="https://twitter.com/TheOnlyMikeQ" target="_blank"><strong>Mike Q</strong></a> is an amazing house DJ/musician that runs one of the most exciting labels in NYC right now, <a href="http://www.qweenbeat.com/" target="_blank"><strong>Qween Beat</strong></a>. Qween Beat is the vanguard of contemporary vogue culture and Vogue Knights is the Monday night vogue party that Mike Q deejays. It's the return to glamour that we've missed since electroclash. Please dress like an adult—a beautiful, beautiful adult.</p>
          <p><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Good+Room+brooklyn" target="_blank"><strong>Good Room</strong></a>: Formerly the Polish discotheque and (awful sound) rock venue, Europa has been transformed into a, well, discotheque with great sound. Hosting diverse DJs from all the DFA usual suspects to the<strong> <a href="https://soundcloud.com/the-carry-nation" target="_blank">Carry Nation</a> </strong>party to Tropical Goth night (no, we don't know what the deal is with all the tropical themed club shit... the zeitgeist must enjoy bright colors), Good Room is a safe bet for non-excruciating club culture. The 94th Precinct is right down the street, so keep your outdoor moronicisms to a minimum.</p>
          <p><a href="http://clubshade.com/" target="_blank"><strong>Club Shade</strong></a><strong>:</strong> Sometimes things are so beautiful, so pure, so transcendent and good that they can only be described as "a roving queer/fashion crowd party that's hella cool."</p>
          <p><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Sugar+Hill+Disco+%26+Restaurant+brooklyn" target="_blank"><strong>Sugar Hill Disco &amp; Restaurant</strong></a>: Open since 1979 and, according to Akesha Freeman (her father, Eddie, owns the place), "the longest black owned running nightclub in Brooklyn," Bedstuy's Sugar Hill is a goddamned wonder. They don't have a website because running a website is a pain in the ass and you really shouldn't be forced to do so just because you run a popular bar. Great comfort food, excellent dance space and periodic home to some of the most fun parties NYC has offered in years; <a href="http://mean.red/" target="_blank"><strong>Mean Red</strong></a> and <strong><a href="http://www.tikidisco.com/" target="_blank">Tiki Disco</a></strong>.<a href="http://www.tikidisco.com/" target="_blank"></a></p>
          <p><strong>Afterhours</strong>
            <br />OK. This gets tricky. We trust you. We totally don't think you're a cop. We also don't think you're a thief, a coke vulture, or a sexual predator. But how do we tell you about afterhours without risking an influx of all of the above? We're going to do this. Follow Slutlust, Dances, Prince Terrence, <strong><a href="http://www.burymeinbrooklyn.com/" target="_blank">Bury Me in Brooklyn</a></strong>, and The Favor on Instagram. See what happens. Try prayer. Don't be a cop and, for the love of Christ, don't ask your bartender "what's open" at 4 AM and then say "I thought this was the city that never sleeps" when they say, "I dunno, man." They'll invite you if you seem like someone they'd want to hang out with, grinding your teeth in unison at five in the morning while the world's erections give up the ghost. Afterhours can and will happen... but they're invite only.
            <a name="Eat"></a>
          </p>
          <h2 data-scroll="true" data-scroll-action="#image#2">Where to Eat</h2>
          <p>It's easy to be a cynic when talking about food in New York; jokes line up about foodies who recommend baby scorpions on the half-shell, or crouton ice-cream or whatever, but that's kind of reductive. Food is necessary and in New York, it's fucking great. People come from all over this stupid planet to work in and worship at our restaurants. Cuisines intertwine and diverge here to such a degree that purists and alchemists alike can find places to fall in love with, or be offended by, next door to one another. It's crazy out there, the best advice we can offer is, "put your mouth on wild things."</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=B%26H+Dairy+" target="_blank">B&amp;H Dairy</a>:</strong> Eighty years old and still basically the coolest restaurant in New York. It serves delicious vegetarian kosher and a bit of seafood (tuna and whitefish mainly), I go for the borscht and the crowd. The tiny countertop joint attracts old Jews and squatters in equal measure. Handsome Dick Manitoba (of the Dictators and Manitoba's Bar fame) can be found ordering matzo brei, surrounded by little elderly ladies chatting with the remnants of boho East Village. B&amp;H was closed for months because of a devastating fire on the block that killed two. Go and support. Get the grilled cheese and soup special. Last time we were there, Parker Posey dropped by to say hi to the counter guy and there was a vagrant in the corner playing "Enola Gay" by Orchestral Maneuvers in the Dark on repeat for the entire hour we were there. Truly the finest of dining establishments.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Superiority+Burger+brooklyn" target="_blank">Superiority Burger</a>:</strong> It's new and massively hyped right now, so it may be a wait to get in to this vegetarian fast food joint. But it's run by dude was in Born Against and, as fucking tired and trite as this ALWAYS sounds, the burgers are great even if you aren't a vegetarian!!!</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Roberta's+brooklyn" target="_blank">Roberta's</a>: </strong>Years ago, Brandon Hoy—now owner of Roberta's, then dude from hard rock band Alabama Black Snake—said he was going to open a pizza place in Bushwick. Everyone kind of assumed that he was going to get very broke very quickly, but now he can buy and sell both me and you a hundred times over. The pizza is very good. Go. Give him your money. They also have regular parties in the back yard during the summer that are one of the few exceptions to the "don't bother standing in lines" rule.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Jahlookova+Health+Mart+new+york+city" target="_blank">Jahlookova Health Mart</a>: </strong>Inexpensive and good-as-hell Harlem juice bar that's widely considered the best in the area. Also Ital food that's fresh and won't kill your budget.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Dar+525+new+york+city" target="_blank">Dar 525</a>: </strong>Run by two Syrian/Turkish/Brazilian cousins, Dar 525 is a Mediterranean joint in Williamsburg that has a fleet of delivery guys parked outside constantly running in and out, so popular is their take out. Consequently, even though this is easily one of the best places in Brooklyn, you can usually find a place to sit. Get the pistachio pizza, which is just bread, pistachio, seven cheeses, rosemary, olive oil, and onions. It's dope.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=New+Asha+new+york+city" target="_blank">New Asha</a>:</strong> You may well not end up on Staten Island. But maybe you're dating a cop, so maybe you end up on Staten Island. The people we know who work for the tabloids, and therefore make semi-regular sojourns to New York's Weirdest Borough, all go to New Asha. It's a Sri Lankan storefront that serves curries. Shit. While looking for a hyperlink we just saw that New Asha was featured on an Anthony Bourdain show. Oh well, I guess she probably knows curries, but if you have some sort of prestige issue with eating at joints featured on TV shows, the neighborhood, Tompkinsville, is rife with plenty of other wonderful Sri Lankan cuisine.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Pakistan+Tea+House+new+york+city" target="_blank">Pakistan Tea House</a>:</strong> Reasonable people can argue about their favorite place to grab quick and cheap Pakistani fare, but this Tribeca late night-spot is our go-to. Of course, Pak Punjab on 2nd Ave and 3rd Street and <a href="https://www.facebook.com/PunjabiGroceryDeli/" target="_blank"><strong>Punjabi Grocery and Deli</strong></a> are also perfectly delicious and just right for your late night budget eating.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=La+Savane+new+york+city" target="_blank">La Savane</a>:</strong> Wonderful West African cuisine joint owned by two former cab drivers. Cheap, absolutely delicious stews and fish and whatnot. No website (and we don't link to Yelp cos that shit is for squares and extortionists) because they are wild and free like the summer wind across the plains, but it's on 239 W. 116th Street and is well worth the trip. They don't serve booze and they don't want you to bring any. You can go a couple hours without a drink probably.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Ariana+Kebab+new+york+city" target="_blank">Ariana Kebab</a>:</strong> Afghan food is an under-appreciated wonder and New York has its share of the better ones. A combination of some the best aspects of Indian food and your better Middle Eastern kebab house, Afghan cuisine offers an exceptionally creamy take on rice, meat, and pumpkin dishes. The music is good, the staff is welcoming in a "take no bullshit" way, and the food is unlike anything you've probably had. Order a couple mains, but go heavy on the sides and appetizers. Put sauce on everything.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Kunjip+new+york+city" target="_blank">Kunjip</a>:</strong> We'd be remiss in our duty not to recommend a visit to Koreatown. It's basically one block (West 32nd between 5th Ave and the intersection of 6th Ave and Broadway), but there's a lot there. It's pretty vibrant 24/7 and the food is delicious and the nail salons are places the <em>Times</em> writes <a href="http://www.nytimes.com/2015/05/10/nyregion/at-nail-salons-in-nyc-manicurists-are-underpaid-and-unprotected.html" target="_blank">really long and sad articles</a> about. Kunjip, open 24 hours and usually packed, has some of the best spicy food in the neighborhood.</p>
          <p><strong>Street Food</strong><br />Avoid the pretzels, but eat the hot dogs because, yes, they are gross, but you're here. Try any of the halal and Indian stands. Look for the ones with longest lines but don't be snob if you just want a cheap gyro. Mexican ones are good, but best in Queens. There's one not too far from the VICE office on the corner of Bedford and North 7th in Williamsburg that makes legit gorditas. We eat at food trucks all the time because they're generally cheap and yummy, and at lunchtime, you should follow the suits or the hardhats.<a name="Transcendence"></a></p>
          <h2  data-scroll="true" data-scroll-action="#image#6">Where to Achieve Something Akin to Transcendence</h2>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Cathedral+of+Saint+John+of+The+Divine+new+york+city" target="_blank">Cathedral of Saint John of the Divine</a>:</strong> If you're doing New York correctly, at some point you're going to be consumed with a devastating guilt and the need to prostrate yourself before a cross. You should totally do that. Cathedral of Saint John of the Divine is architecturally stunning. If you're Episcopalian or something close, go and get right with Jesus, sinner. If you're not, go marvel at what faith can build and then go visit the gift shop.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=The+Dream+House+new+york+city" target="_blank">The Dream House</a>:</strong> Another favorite house of worship is composer La Monte Young and artist, Marian Zazeela's Dream House. Usually on Church Street and temporarily an installation on <a href="http://www.diaart.org/exhibitions/main/131" target="_blank">West 22nd</a>, Dream House is a room. Just a room, shut off from everything. A room with "continuous frequencies of sound and light." There are some hanging shapes that you can look at or not. Basically, you lie in this room, you shut the fuck up (TURN YOUR PHONE OFF), and lose yourself. Or find yourself, man. You're not going to know till you try. Dream House is not for everyone. Nothing happens and if your own existence is itself a source of anxiety for you, this may not be your jam. <i>But what if it is.</i></p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=The+Cloisters+new+york+city" target="_blank">The Cloisters</a>:</strong> The Cloisters are perfect for getting in touch with your Arthurian id. This "medieval treasure in Northern Manhattan" is an architectural mish-mash of both the secular and the divine. Just go and look at the art and pretend you're a princess and will die of rickets at 26. Oh, right, BY THE WAY. The Cloisters is in Fort Tryon Park. Is Fort Tryon Park where the so-fucking-cool-you-could-just-punch-a-dragon <a href="http://www.whidc.org/festival/home" target="_blank">Medieval Festival</a> is held? Sweet baby Merlin, it is.</p>
          <p><strong><a href="http://www.nycgovparks.org/parks/fort-greene-park/monuments/1222" target="_blank">Prison Ship Martyr's Memorial in Fort Greene Park</a>:</strong> A monument to the roughly 11,500 American prisoners of war who died in the British prison ships during the Revolutionary War. Figures memorably in both Spike Lee's "She's Gotta Have" it and the Diane Paragas/Nelson George documentary, <a href="http://www.bkboheme.com/" target="_blank">Brooklyn Boheme</a>. Go and look at it and think about death and art and the struggle.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Woodlawn+Cemetery+new+york+city" target="_blank">Woodlawn Cemetery</a>:</strong> At some point, before, during, or after your visit to New York City, you are going to die. Not the best news and presumably not really news. If we're the first to break it to you, apologies. But you're here now, so why not make the most of it by spending a day at one of the most sublime properties in the city while thinking about all those lost souls (Melville, Ellington, Elizabeth Cochran Seaman a.k.a. Nellie Bly, etc.) whose remains are currently Netflixing and chilling on these grounds. Appreciate your every breath, you wonderful, temporary meat box.</p>
          <a name="Sports"></a>
          <h2 data-scroll="true" data-scroll-action="#image#5">Sports</h2>
          <p>As every New Yorker who loves sports will tell you until the bar calls last call, "New York City is a sports town." Sweet Jesus, are we a sports town. Even our punks make exceptions in their disdain for money and the System to cheer for the Mets or even, god help them, the Yankees. Crying about the Knicks is a unifying factor in a city made of people whose best friends are made by Apple. If sports is your hobby of choice or maybe you just have a horrific gambling addiction, we got you covered.</p>
          <p><strong>Where to Watch Live Soccer:</strong> Of course you can go to Yankee Stadium (home to NYCFC) or to Red Bull Arena (home to the NY Red Bulls) to watch MLS, but no place offers outstanding Mexican food like the Red Hook ball fields. Here amateurs participate in rec leagues, but the real attraction is the food.</p>
          <p><strong>Where to Play Basketball:</strong> "The Cage" on W. 4th offers the chance for amateurs to intermingle with professionals. NBA pros have been known to play a few games here.</p>
          <p><strong>Where to Watch Basketball:</strong> Sure you can go to Madison Square Garden or Barclays Center, but real basketball fans go to Rucker Park in Harlem to watch some of the best streetball in the world.</p>
          <p><strong>Where to Watch Baseball:</strong> Where do many former professional baseball players from the Dominican Republic end up playing once their major league dreams are extinguished? At the <a href="http://www.facebook.com/Pedrin-Zorrilla-Baseball-League-365940706832598/" target="_blank"><strong>Pedrin Zorrilla Baseball League</strong></a> in Brooklyn. City Line Park is their main field.</p>
          <p className="p6"><strong>Best Pro Stadium:</strong> Citi Field cost less to build than the new Yankee Stadium, and yet it houses the best atmosphere of any New York area pro stadium. It's got the best food (Shake Shack and Blue Smoke), best beer selection, and now it's even home to the best baseball team in the city. Tip: Make sure you grab the 7 express train—not local—on the way to Queens. It will save you about 15 minutes of travel time.</p>
          <p><strong>Sports Bars<br /></strong>Maybe you prefer your sports in the company of drunk strangers. If you're loyal to a particular team, odds are high there's a bar somewhere in the five boroughs where you'll be able to congregate with other fans of that team. For our purposes, we're sticking to bars that lobby a specific sport. But as a general rule, avoid frat-friendly bars in the Village like 13th Step or Village Pourhouse.</p>
          <p><strong>For Baseball: </strong>Irish born owner Shaun Clancy has established <a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Foley%27s+NY+Pub+and+Restaurant" target="_blank"><strong>Foley's NY Pub and Restaurant</strong></a> as the best baseball bar in the city. Consider the decor a mini Hall of Fame.</p>
          <p><strong>For Basketball:</strong> A departure from the type of bar we would normally recommend, <strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Stout+NYC" target="_blank">Stout NYC</a></strong> is a  /great place to catch a game for two reasons. The first is that it's near Madison Square Garden, so it's easy to get swept up in the aftermath of a big game. The other is that people who work for the NBA have been known to hang out there. You never know what you'll overhear or who you might run into.<br /></p>
          <p><strong>For Football:</strong> Solid cocktails, cheap beer, and decent eats make <a href="http://www.boilermakernyc.com/#home" target="_blank"><strong>Boilermaker</strong></a> especially great during its five-hour-long Sunday football happy hour. Get the Boilermaker bucket, which includes a six-pack of Miller High Life and six shots.</p>
          <p><strong>For Soccer:</strong> Between the hot toddies and the backyard beer garden, <a href="http://ionabrooklyn.com/Welcome.html" target="_blank"><strong>IONA</strong></a> elevates the soccer experience. Just kidding. You'll still find fans losing their minds at this Williamsburg Scottish bar, but at least they're doing it while getting some sun and enjoying a warm beverage. The bar opens early Saturdays and Sundays for European soccer.</p>
          <a name="Daytime"></a>
          <h2 data-scroll="true" data-scroll-action="#image#1">What to Do During the Day</h2>
          <p>New York, like a well-trod path over a mountain, is fantastically uncomplicated to navigate on foot. And there's NEVER anything not worth looking at. Even the boring shit will have some good graffiti on it or <a href="https://www.vice.com/read/pizza-rat-and-the-city-921" target="_blank">Pizza Rat</a> living his best life on the sidewalk or something. Go see a documentary at the <a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Maysles+Documentary+Center+new+york+city" target="_blank"><strong>Maysles Documentary Center</strong></a> on 127/128th and then walk from the <a href="http://www.centralparknyc.org/things-to-see-and-do/attract" target="_blank"><strong>Duke Ellington Statue</strong></a> on 110th down to Columbus Circle. Hell, keep going down to Houston.</p>
          <p>Walk the distance from the <a href="http://www.hudsonriverpark.org/explore-the-park/activities/tribeca-skatepark" target="_blank"><strong>Hudson River Skate Park</strong></a> to the <a href="http://www.poetshouse.org/" target="_blank"><strong>Poets House</strong></a>. I'm operating under the assumption that you are awesome and love poetry and skateboarding in equal measure.</p>
          <p>The <a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Mellow+Pages+Library+new+york+city" target="_blank"><strong>Mellow Pages Library</strong></a>, currently operating within DIY venue/community space Silent Barn, is a free lending library where there is no membership, no charge, and is entirely donation based. There are regular readings and art shows. It's like all libraries, but maybe a bit more so on account of the freak flags flying and charged atmosphere.</p>
          <p>Go to <a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=William+F+Moore+Park+new+york+city" target="_blank"><strong>William F Moore Park</strong></a>, get some Italian ice from the <strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Lemon+Ice+King+of+Corona+new+york+city" target="_blank">Lemon Ice King of Corona</a> </strong>(as seen on King of Queens!) and go watch the older gentlemen of the neighborhood engage in the sport of (lemon ice) kings: bocce.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=The+Frick+new+york+city" target="_blank">The Frick</a>:</strong> Museums are fine. I mean they are essential and you should go to them, but you sort of already know that. The Frick can set the stage for your later fan/slash-fic reenactment of all your favorite Gilded Age literature/mini-series. The Fifth Avenue museum was Henry Clay Frick's NYC residence and you can still feel the amorality pulsating from the gorgeous walls. He probably ate a union worker's baby in every room.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Fresh+Kills+Park+new+york+city" target="_blank">Fresh Kills Park</a>:</strong> Fresh Kills Park on Staten Island is one of the coolest things, both in theory and practice, you can do while visiting the city. It's a park in progress, built upon what was once the largest landfill in the world. Imagine a rich and rolling savannah covering, by impenetrable caps of plastic and soil, an ancient and potentially explosive trash-heap. They keep the landfill gas from endangering everything through a series of pipes and wells that you can see poking out from the brush. It's basically the most hope-inspiring piece of real estate you may ever see in your lifetime.</p>
          <a name="Music"></a>
          <h2 data-scroll="true" data-scroll-action="#image#3">Places to Hear Music</h2>
          <p>New York invented punk but nobody thinks New York makes the best punk now. New York invented hip-hop but only a few think that New York makes the best hip-hop now. But frankly seeing pretty good stuff within the city's boundaries feels historic and it is really VERY easy to catch amazing music. And if much of it is indebted to New York's storied past (be it Cro Mags or Wu Tang or Blondie or Ronnie Spector), there's more than a fair share of young blood malcontents (both native and transplant) making, or at least admirably striving to make, their own mark.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Saint+Vitus+new+york+city" target="_blank">Saint Vitus</a>:</strong> Vitus has developed a well-deserved international reputation for being the metal venue in New York City. It's done so by dint of smart—but not snobbish—booking, decent sound, and staff who aren't dicks. Plus, the booze is cheap and they don't rip off the bands. There's also the occasional goth and hardcore show and god knows they're suckers for terrible pop punk bands reuniting.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=The+Grand+Victory+new+york+city" target="_blank">The Grand Victory</a>:</strong> An unprepossessing bar with little décor and an American flag draped on the back of the stage. One of the few independent bookers left in the city that still snags bigger bands, pays fairly, and books local worthy-but-not-hyped bands.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Tender+Trap+new+york+city" target="_blank">Tender Trap</a>:</strong> Tender Trap is a dance/hip-hop tavern owned by Ryan Virag and Darryl Nau. Nau is a professional BMX rider, not Andrew WK, so please don't mistake him for him. He's also possibly THE NICEST MAN IN NEW YORK CITY. Like, unnervingly so. The club is a dance/hip-hop bacchanalia; skate ramp, bar go-go dancers, consistently great DJs, and live music. Perfect for dancing without the mega club/mean door people vibe.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Palisades+new+york+city" target="_blank">Palisades</a>: </strong>Located between Bed-Stuy and Bushwick, the music venue and art space embraces all genres, and won't charge you a ton to enjoy the bands.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=the+bell+house+new+york+city" target="_blank">The Bell House</a>:</strong> Opened in a converted Gowanus warehouse in 2008, The Bell House has the space to host big dance parties and a broad range of acts. In the last year alone they've seen everything from hip-hop to indie-pop to live album recordings, along with some musically-inclined comedians showing off secret talents.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Trans-Peco+new+york+city" target="_blank">Trans-Pecos</a>:</strong> Ridgewood all ages joint by DIY industrialist, Todd Patrick. Extremely thoughtfully curated mix of high art, avant-noise and community involvement. The curators have very deep roots in the New York music scene and draw in a diverse range of acts.</p>
          <p><span className="s2"><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=ABC+No+Rio+new+york+city" target="_blank">ABC No Rio</a>:</strong></span> "No Racism, No Sexism, No Bullshit." The original LES all-ages venue. Founded in 1980, ABC No Rio, besides its MANY community activities, has consistently had great Saturday afternoon hardcore/punk matinees. It's worth checking out for the music and the history and the backyard. Records are sold cheap in the back of the venue room. Shows are generally around $8, which considering it's 2015, is insanely cheap. The crowd is obviously wonderful.</p>
          <a name="Shopping"></a>
          <h2 data-scroll="true" data-scroll-action="#image#4">Shopping</h2>
          <p>Shopping in New York City used to be simple. You bought drugs on the street, your glasses at <a href="http://www.fabulousfannys.com/" target="_blank"><strong>Fabulous Fanny's</strong></a>, and everything else at the Virgin Megastore in Union Square. Now, the internet has torpedoed the established order, there are so many more options. For the love of god don't buy drugs on the street. You should still get your glasses at Fanny's, though.</p>
          <p><strong><a href="http://www.facebook.com/rebelrousershopnyc" target="_blank">Rebel Rouser</a> + <a href="http://www.websta.me/n/rat_king_emporium?lang=en" target="_blank">Rat King Emporium</a>:</strong> Two shops in Flea Market Alley, a grouping of shipping containers in Bushwick where you can buy books, bikes, and punk-rock action figures. There's even a radio station-KPISS, named after the former resident of the storage unit who'd piss in jars and never throw said jars away. Rebel Rouser focuses on LPs and 45s of the garage/punk/oldies variety and rare books in the noir/horror vein. Rat King (the province of local rock legend and <a href="http://www.vice.com/read/andy-animal-sensuous-candles" target="_blank">YouTube Yankee Candle reviewer</a>, Andy Animal) focuses on the novelty end of the Rat Fink/x-ray glasses spectrum of our short time here. The entire alleyway is both well worth your time/money and it's really odd/wonderful that it exists at all.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Housing+Works+Bookstore" target="_blank">Housing Works Bookstore</a>:</strong> Fantastic selection of books at more than reasonable prices. Main draw, however, is the impressive variety of readings. We've seen tributes to Saul Bellow, readings with Mr. T Experience's Dr. Frank, and Chris Gethard. The Moth readings regularly take place here, too. The store is also part of the larger Housing Works organization that raises money for AIDS/HIV care and advocacy.</p>
          <p><strong><a href="http://musicinn.nyc/">Music Inn</a>/<a href="http://www.ctrl-mod.com/" target="_blank">Control</a>:</strong> Two music stores in different neighborhoods that offer wildly different services and satisfy the same need. Music Inn sells world music instruments and Control's bag is vintage and rare analog and digital synthesizers. Both provide essential services for niche artists that help make this city pulse and vibrate, both are pretty much unparalleled at what they do within the city, and both are full of staff and clientele that are unlikely to make eye contact with you.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Other+Music+new+york+city" target="_blank">Other Music</a>:</strong> The well-informed staff of this record store has such good taste, it's not uncommon for customers to buy a recording of whatever happens to be playing when they walk in. The staff also makes a habit of writing reviews for new releases, making the path to discovery a little easier. They specialize in underground, rare, and experimental music.<br /></p>
          <p><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Original+Products+Botanica" target="_blank"><strong>Original Products Botanica</strong></a>: A Bronx spirituality and occult store founded in 1959 is perhaps counter-intuitive, but maybe if we had better intuition we'd be better wiccans. This "Home Depot of spirituality" does spiritual consultations in person or via Skype. Sure you talk the witchy goth talk, but perhaps it's time you walk the witchy goth walk. It's difficult to discuss a wide-ranging new age emporium without sounding condescending, but this place is rad as Pan. Go take care of your Tarot card/anointing oil needs.</p>
          <p><strong><a href="http://ingodwetrustnyc.com/">In God We Trust</a>: </strong>Jewelry and Men and Woman's clothing shop with stores in Williamsburg, Greenpoint, and SoHo. They focus on New York designers and we've gotten many of our wardrobe staples there. It's where we do most our holiday/birthday shopping. The card holders and money clips are great presents for parents and people you barely know.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=Atmos+NYC" target="_blank">Atmos</a>:</strong> Harlem sneakerhead's paradise. They treat sneakers like the fine art they are. If humanity had evolved faster, Michelangelo would have designed sneakers and the Pope would have been like, "good job." We at VICE feel entirely comfortable with this statement because it is true.</p>
          <p><strong><a href="http://www.google.com/search?q=Tropical+128+new+york+city&amp;oq=Tropical+128+new+york+city&amp;aqs=chrome..69i57.3590j0j4&amp;sourceid=chrome&amp;es_sm=91&amp;ie=UTF-8#q=The+Baroness+NYC" target="_blank">The Baroness</a>:</strong> Even the most vanilla of us occasionally likes to be rolled in a rug and stepped on by the staff of American Apparel. It's important to take the edge off in this life. But for the more experienced members of the dom/sub community, it's vital to dress the part. The Baroness has been making high quality latex outfits since 1995 so go and adorn yourself in your one true skin. As to their FAQ, Cat Suits are not part of their line but they will custom make one for $800 if you insist on being basic.</p>
          <a name="Around"></a>
          <h2 data-scroll="true" data-scroll-action="#image#7">Getting Around</h2>
          <p>You have five basic options because we're not counting pedi-cabs. The buses are great but may be confusing for a first time visitor. And for sure take a ferry somewhere. You'll need the <a href="http://www.siferry.com/" target="_blank"><strong>Staten Island Ferry</strong></a> to check out Fresh Kills Park and it's worth it on its own merits.</p>
          <p><strong>Walking:</strong> Fun! Easy! Tiring!</p>
          <p><strong>Cabs: </strong>Get in the cab first, then tell them where to go. Be polite but this is part of their job and if they didn't want to go out of their way, they should have turned their light off. Of course, if they tell you their shift is over and you've got time to wait for another cab, have a heart. But that's not entirely on you. Tip 20 percent unless they are terrible, but considering how drunk you probably are, tip them 20 percent anyway.</p>
          <p><strong>Uber: </strong>Everyone who doesn't care about politics loves them. White progressive friends hate them. Black progressive friends are like, "Cabs don't pick me up. What the fuck am I supposed to do?" They're crazy expensive, they're changing the world, you already have the app on your phone and when you need them most, they'll be there for you.</p>
          <p className="p1"><strong>Citi Bike:</strong> Utopian vision/moving advertisement for a bank, Citi Bike, is best described in one phrase: "Could have been worse." Yes, it's mainly in rich neighborhoods. Yes, we are drowning in Swedish dads biking on the sidewalk and yes, you'll be riding around on an advertisement for a bank. Conversely, it could be worse. It's a bike sharing system where all the bikes haven't been stolen or vandalized beyond recognition, traffic hasn't been noticeable impacted, and the Swedish dads are unfailingly polite.</p>
          <p><strong>Subway:</strong> Oh MTA, thorn in our side, joy of our hearts. It runs 24 hours, is reasonably clean and safe, and has THE most badass union in recent memory. Still, when you're five minutes late and the train stalls out for another five, or a line isn't running, you'll hate the MTA with feelings unparalleled. A beautiful object arouses fierce passions. Objectively, the subway is the best. You're in New York City. Go underground and get to know our fair population. Tip the Showtime Dancers, please.</p>
          <p><em>Special thanks to Zachary Lipez for compiling all our recommendations.</em><br /></p>
          <a href="#alexandros_grigoropoulos" onClick={this.detailLink.bind(this)} style={{display: "none"}}>Alexandros Grigoropoulos</a>
        </div>
      </div>
    );
  }
}

